/**
 * Список всех королев для симулятора.
 * Каждая королева: photo, fashion, design, performance, comedy, acting, improv, lipsync (1–15).
 */
window.queensDb = {
    'Arrietty': { photo: 'images/ArriettyS17CastMug.webp', fashion: 13, design: 13, performance: 8, comedy: 5, acting: 6, improv: 5, lipsync: 5 },
    'Kori King': { photo: 'images/KoriKingS17CastMug.webp', fashion: 8, design: 6, performance: 7, comedy: 9, acting: 9, improv: 9, lipsync: 9 },
    'Lydia B Kollins': { photo: 'images/LydiaBKollinsS17CastMug.webp', fashion: 12, design: 10, performance: 12, comedy: 11, acting: 9, improv: 11, lipsync: 12 },
    'Jewels Sparkles': { photo: 'images/JewelsSparklesS17CastMug.webp', fashion: 12, design: 10, performance: 12, comedy: 11, acting: 10, improv: 11, lipsync: 11 },
    'Acacia Forgot': { photo: 'images/AcaciaForgotS17CastMug.webp', fashion: 7, design: 7, performance: 5, comedy: 8, acting: 7, improv: 8, lipsync: 7 },
    'Crystal Envy': { photo: 'images/CrystalEnvyS17CastMug.webp', fashion: 9, design: 10, performance: 10, comedy: 6, acting: 9, improv: 6, lipsync: 9 },
    'Hormona Lisa': { photo: 'images/HormonaLisaS17CastMug.webp', fashion: 7, design: 8, performance: 6, comedy: 7, acting: 10, improv: 7, lipsync: 4 },
    'Joella': { photo: 'images/JoellaS17CastMug.webp', fashion: 5, design: 5, performance: 6, comedy: 7, acting: 7, improv: 7, lipsync:7 },
    'Lana Ja\'Rae': { photo: 'images/LanaJaRaeS17CastMug.webp', fashion: 8, design: 6, performance: 8, comedy: 8, acting: 7, improv: 7, lipsync: 12 },
    'Lexi': { photo: 'images/LexiS17CastMug.webp', fashion: 11, design: 11, performance: 13, comedy: 11, acting: 12, improv: 11, lipsync: 12 },
    'Lucky Starzzz': { photo: 'images/LuckyStarzzzS17CastMug.webp', fashion: 8, design: 4, performance: 5, comedy: 6, acting: 6, improv: 6, lipsync: 5 },
    'Onya Nurve': { photo: 'images/OnyaNurveS17CastMug.webp', fashion: 9, design: 10, performance: 14, comedy: 15, acting: 14, improv: 14, lipsync: 10 },
    'Sam Star': { photo: 'images/SamStarS17CastMug.webp', fashion: 12, design: 14, performance: 12, comedy: 10, acting: 11, improv: 11, lipsync: 10 },
    'Suzie Toot': { photo: 'images/SuzieTootS17CastMug.webp', fashion: 10, design: 8, performance: 13, comedy:10, acting: 14, improv: 10, lipsync: 8 },
    'Athena Dion': { photo: 'images/AthenaDionS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8 },
    'Briar Blush': { photo: 'images/BriarBlushS18CastMug.webp', fashion: 6,  design: 7,  performance: 8,  comedy:7, acting: 6, improv: 6, lipsync: 9 },
    'Ciara Myst':{ photo: 'images/CiaraMystS18CastMug.webp', fashion: 9,  design: 8,  performance: 6,  comedy: 7, acting: 6, improv: 6, lipsync: 6 },
    'Darlene Mitchell':{ photo: 'images/DarleneMitchellS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8 },
    'DD Fuego':{ photo: 'images/DDFuegoS18CastMug.webp', fashion: 5,  design: 4,  performance: 5,  comedy: 6, acting: 6, improv: 6, lipsync: 4 },
    'Discord Addams':{ photo: 'images/DiscordAddamsS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8 },
    'Jane Don\'t':{ photo: 'images/JaneDontS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8 },
    'Juicy Love Dion':{ photo: 'images/JuicyLoveDionS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8 },
    'Kenya Pleaser':{ photo: 'images/KenyaPleaserS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8 },
    'Mandy Mango':{ photo: 'images/MandyMangoS18CastMug.webp', fashion: 6,  design: 5,  performance: 8,  comedy: 6, acting: 6, improv: 6, lipsync: 9 },
    'Mia Starr':{ photo: 'images/MiaStarrS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8 },
    'Myki Meeks':{ photo: 'images/MykiMeeksS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8 },
    'Nini Coco':{ photo: 'images/NiniCocoS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8 },
    'Vita VonTesse Starr': { photo: 'images/VitaVonTesseStarrS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8 },
    'Amanda Tori Meating': { photo: 'images/AmAndaToriMeatingS16CastMug.webp', fashion: 6, design: 6, performance: 9, comedy: 7, acting: 7, improv: 7, lipsync: 8 },
    'Dawn':{photo: 'images/DawnS16CastMug.webp', fashion: 11, design: 11, performance: 8, comedy: 8, acting: 8, improv: 7, lipsync:6 },
    'Geneva Karr':{photo: 'images/GenevaKarrS16CastMug.webp', fashion: 6, design: 6, performance: 10, comedy: 6, acting: 6, improv: 6, lipsync:12 },
    'Hershii LiqCour-Jeté':{photo: 'images/HershiiLiqCour-JeteS16CastMug.webp', fashion: 4, design: 4, performance:6, comedy: 7, acting: 7, improv: 7, lipsync:4 },
    'Megami':{photo: 'images/MegamiS16CastMug.webp', fashion: 7, design: 7, performance:6, comedy: 8, acting: 8, improv: 9, lipsync:10 },
    'Mhi\'ya Iman Le\'Paige':{photo: 'images/MhiPaigeS16CastMug.webp', fashion: 6, design: 6, performance:12, comedy: 8, acting: 6, improv: 7, lipsync:13 },
    'Mirage':{photo: 'images/MirageS16CastMug.webp', fashion: 8, design: 8, performance:10, comedy: 6, acting: 4, improv: 6, lipsync:11},
    'Morphine Love Dion':{photo: 'images/MorphineLoveDionS16CastMug.webp', fashion: 8, design: 8, performance:14, comedy: 9, acting: 7, improv: 9, lipsync:14},
    'Nymphia Wind':{photo: 'images/NymphiaWindS16CastMug.webp', fashion: 14, design: 14, performance:11, comedy: 9, acting: 9, improv: 9, lipsync:11},
    'Plane Jane':{photo: 'images/PlaneJaneS16CastMug.webp', fashion: 10, design: 10, performance:11, comedy: 12, acting: 10, improv: 12, lipsync:9},
    'Plasma':{photo: 'images/PlasmaS16CastMug.webp', fashion: 9, design: 7, performance:11, comedy: 11, acting: 13, improv: 10, lipsync:7},
    'Q':{photo: 'images/QS16CastMug.webp', fashion: 13, design: 13, performance:7, comedy: 9, acting: 10, improv: 9, lipsync:6},
    'Sapphira Cristál':{photo: 'images/SapphiraCristS16CastMug.webp', fashion: 12, design: 10, performance:11, comedy: 13, acting: 11, improv: 13, lipsync:9},
    'Xunami Muse':{photo: 'images/XunamiMuseS16CastMug.webp', fashion: 8, design: 8, performance:8, comedy: 8, acting: 8, improv: 8, lipsync:6},
    'Dulce':{photo: 'images/DulceCDR6CastMug.webp', fashion: 7, design: 7, performance:10, comedy: 7, acting: 9, improv: 6, lipsync:10},
    'Eboni La\'Belle':{photo: 'images/EboniCDR6CastMug.webp', fashion: 10, design: 6, performance:14, comedy: 11, acting: 13, improv: 12, lipsync:15},
    'Hazel':{photo: 'images/HazelCDR6CastMug.webp', fashion: 9, design: 8, performance:9, comedy: 5, acting: 6, improv: 5, lipsync:8},
    'Karamilk':{photo: 'images/KaramilkCDR6CastMug.webp', fashion: 9, design: 10, performance:11, comedy: 9, acting: 9, improv: 7, lipsync:10},
    'Mya Foxx':{photo: 'images/MyaFoxxCDR6CastMug.webp', fashion: 8, design: 7, performance:7, comedy: 13, acting: 9, improv: 13, lipsync:5},
    'Paolo Perfección': {photo: 'images/PaoloPerfeccionCDR6CastMug.webp', fashion: 7, design: 7, performance:6, comedy: 6, acting: 5, improv: 7, lipsync:5},
    'PM':{photo: 'images/PMCDR6CastMug.webp', fashion: 6, design: 4, performance:13, comedy: 8, acting: 8, improv: 11, lipsync:12},     
    'Saltina Shaker':{photo: 'images/SaltinaShakerCDR6CastMug.webp', fashion: 11, design: 5, performance:13, comedy: 13, acting: 13, improv: 10, lipsync:12},
    'Sami Landri':{photo: 'images/SamiLandriCDR6CastMug.webp', fashion: 11, design: 8, performance:9, comedy: 11, acting: 9, improv: 13, lipsync:9},
    'Star Doll':{photo: 'images/StarDollCDR6CastMug.webp', fashion: 7, design: 6, performance:10, comedy: 7, acting: 7, improv: 7, lipsync:11},
    'Van Goth':{photo: 'images/VanGothCDR6CastMug.webp', fashion: 14, design: 15, performance:10, comedy: 8, acting: 8, improv: 8, lipsync:10},
    'Velma Jones':{photo: 'images/VelmaJonesCDR6CastMug.webp', fashion: 10, design: 8, performance:10, comedy: 11, acting: 10, improv: 9, lipsync:8},
    'Bones':{photo: 'images/BonesDRUK7CastMug.webp', fashion: 13, design: 11, performance:12, comedy: 11, acting: 10, improv: 9, lipsync:13},
    'Elle Vosque':{photo: 'images/ElleVosqueDRUK7CastMug.webp', fashion: 11, design: 9, performance:13, comedy: 12, acting: 13, improv: 12, lipsync:10},
    'Catrin Feelings':{photo: 'images/CatrinFeelingsDRUK7CastMug.webp', fashion: 8, design: 9, performance:9, comedy: 10, acting: 12, improv: 10, lipsync:9},
    'Silllexa Diction':{photo: 'images/SilllexaDictionDRUK7CastMug.webp', fashion: 12, design: 10, performance:10, comedy: 8, acting: 7, improv: 8, lipsync:8},
    'Tayris Mongardi':{photo: 'images/TayrisMongardiDRUK7CastMug.webp', fashion: 8, design: 7, performance:13, comedy: 8, acting: 8, improv: 8, lipsync:12},
    'Bonnie Ann Clyde':{photo: 'images/BonnieAnnClydeDRUK7CastMug.webp', fashion: 6, design: 6, performance:10, comedy: 14, acting: 14, improv: 14, lipsync:7},
    'Paige Three':{photo: 'images/PaigeThreeDRUK7CastMug.webp', fashion: 11, design: 9, performance:14, comedy: 6, acting: 11, improv: 6, lipsync:12},
    'Sally™':{photo: 'images/SallyDRUK7CastMug.webp', fashion: 11, design: 12, performance:6, comedy: 7, acting: 12, improv: 7, lipsync:7},
    'Chai T Grande':{photo: 'images/ChaiTGrandeDRUK7CastMug.webp', fashion: 8, design: 8, performance:8, comedy: 7, acting: 6, improv: 7, lipsync:7},
    'Nyongbella':{photo: 'images/NyongbellaDRUK7CastMug.webp', fashion: 7, design: 8, performance:8, comedy: 7, acting: 4, improv: 6, lipsync:8},
    'Viola':{photo: 'images/ViolaDRUK7CastMug.webp', fashion: 7, design: 5, performance:6, comedy: 6, acting: 6, improv: 10, lipsync:7},
    'Pasty':{photo: 'images/PastyDRUK7CastMug.webp', fashion: 5, design: 3, performance:5, comedy: 6, acting:6, improv: 6, lipsync:4},
    'Gawdland':{photo: 'images/GawdlandUKvsTW3CastMug.webp', fashion: 11, design: 9, performance:13, comedy: 10, acting: 13, improv: 10, lipsync:10},
    'Fontana':{photo: 'images/FontanaUKvsTW3CastMug.webp', fashion: 10, design: 8, performance:12, comedy: 9, acting: 12, improv: 9, lipsync:12},
    'Mariah Balenciaga':{photo: 'images/MariahBalenciagaUKvsTW3CastMug.webp', fashion: 7, design: 8, performance:8, comedy: 6, acting: 8, improv: 5, lipsync:7},
    'Kate Butch':{photo: 'images/KateButchUKvsTW3CastMug.webp', fashion: 7, design: 7, performance:11, comedy: 12, acting: 14, improv: 11, lipsync:6},
    'Serena Morena':{photo: 'images/SerenaMorenaUKvsTW3CastMug.webp', fashion: 7, design: 5, performance:4, comedy: 5, acting: 5, improv: 6, lipsync:7},
    'Sminty Drop':{photo: 'images/SmintyDropUKvsTW3CastMug.webp', fashion: 11, design: 11, performance:6, comedy: 5, acting: 6, improv: 4, lipsync:6},
    'Zahirah Zapanta':{photo: 'images/ZahirahZapantaUKvsTW3CastMug.webp', fashion: 6, design: 5, performance:7, comedy: 6, acting: 5, improv: 4, lipsync:7},
    'Minty Fresh':{photo: 'images/MintyFreshUKvsTW3CastMug.webp', fashion: 12, design: 11, performance:10, comedy: 6, acting: 8, improv: 7, lipsync:7},
    'The Only Naomy':{photo: 'images/TheOnlyNaomyUKvsTW3CastMug.webp', fashion: 8, design: 8, performance:4, comedy: 6, acting: 6, improv: 6, lipsync:4},
    'Melinda Verga':{photo: 'images/MelindaVergaUKvsTW3CastMug.webp', fashion: 7, design: 5, performance:12, comedy: 13, acting: 12, improv: 13, lipsync:11},
    'Actavia':{photo: 'images/ActaviaDRUK6CastMug.webp', fashion: 5, design: 6, performance:10, comedy: 7, acting: 7, improv: 5, lipsync:12},
    'Chanel O\'Conor':{photo: 'images/ChanelOConorDRUK6CastMug.webp', fashion: 11, design: 12, performance:9, comedy: 6, acting: 9, improv: 5, lipsync:8},
    'Charra Tea':{photo: 'images/CharraTeaDRUK6CastMug.webp', fashion: 7, design: 7, performance:8, comedy: 9, acting: 8, improv: 10, lipsync:8},
    'Dita Garbo':{photo: 'images/DitaGarboDRUK6CastMug.webp', fashion: 8, design: 6, performance:6, comedy: 6, acting: 4, improv: 6, lipsync:6},
    'Kiki Snatch':{photo: 'images/KikiSnatchDRUK6CastMug.webp', fashion: 6, design: 6, performance:12, comedy: 6, acting: 6, improv: 5, lipsync:12},
    'Kyran Thrax':{photo: 'images/KyranThraxDRUK6CastMug.webp', fashion: 11, design: 10, performance:12, comedy: 13, acting: 13, improv: 12, lipsync:10},
    'La Voix':{photo: 'images/LaVoixDRUK6CastMug.webp', fashion: 10, design: 9, performance:12, comedy: 14, acting:13, improv: 14, lipsync:10},
    'Lill':{photo: 'images/LillDRUK6CastMug.webp', fashion: 12, design: 12, performance:8, comedy: 10, acting:9, improv: 10, lipsync:11},
    'Marmalade':{photo:'images/MarmaladeDRUK6CastMug.webp', fashion: 14, design: 13, performance:9, comedy: 11, acting: 11, improv: 11, lipsync:8},
    'Rileasa Slaves':{photo:'images/RileasaSlavesDRUK6CastMug.webp',fashion:9, design:8, performance:13,comedy:7,acting:12,improv:7,lipsync:14},
    'Saki Yew':{photo:'images/SakiYewDRUK6CastMug.webp',fashion:7, design:6, performance:6,comedy:6,acting:6,improv:6,lipsync:6},
    'Sasha Colby': { photo: 'images/SashaColbyS15CastMug.webp', fashion: 12, design: 13, performance: 14, comedy: 13, acting: 13, improv: 13, lipsync: 14 },
    'Anetra':{ photo: 'images/AnetraS15CastMug.webp', fashion: 11, design: 13, performance: 14, comedy: 9, acting: 13, improv: 10, lipsync: 14 },
    'Luxx Noir London':{ photo: 'images/LuxxNoirLondonS15CastMug.webp', fashion: 13, design: 14, performance: 12, comedy: 12, acting: 11, improv: 12, lipsync: 12 },
    'Mistress Isabelle Brooks':{ photo: 'images/MistressIsabelleBrooksAS10CastMug.webp', fashion: 13, design: 13, performance: 11, comedy: 14, acting: 13, improv: 12, lipsync: 10 },
    'Loosey LaDuca':{ photo: 'images/LooseyLaDucaS15CastMug.webp', fashion: 10, design: 9, performance: 9, comedy: 14, acting: 10, improv: 14, lipsync: 9 },
    'Salina EsTitties':{ photo: 'images/SalinaEsTittiesS15CastMug.webp', fashion: 6, design: 6, performance: 8, comedy: 9, acting: 8, improv: 8, lipsync: 9 },
    'Marcia Marcia Marcia':{ photo: 'images/MarciaMarciaMarciaS15CastMug.webp', fashion: 9, design: 9, performance: 11, comedy: 10, acting: 12, improv: 11, lipsync: 11 },
    'Malaysia Babydoll Foxx':{ photo: 'images/MalaysiaBabydollFoxxS15CastMug.webp', fashion: 9, design: 9, performance: 8, comedy: 9, acting: 13, improv: 8, lipsync: 8 },
    'Spice':{ photo: 'images/SpiceS15CastMug.webp', fashion: 10, design: 5, performance: 10, comedy: 6, acting: 7, improv: 6, lipsync: 6 },
    'Jax':{ photo: 'images/JaxS15CastMug.webp', fashion: 7, design: 6, performance: 13, comedy: 8, acting: 6, improv: 7, lipsync: 14 },
    'Aura Mayari':{ photo: 'images/AuraMayariS15CastMug.webp', fashion: 7, design: 7, performance: 11, comedy: 7, acting: 4, improv: 7, lipsync: 10 },
    'Robin Fierce':{ photo: 'images/RobinFierceS15CastMug.webp', fashion: 7, design: 8, performance: 6, comedy: 5, acting: 5, improv: 5, lipsync: 7 },
    'Amethyst':{ photo: 'images/AmethystS15CastMug.webp', fashion: 7, design: 5, performance: 8, comedy: 9, acting: 6, improv: 7, lipsync: 10 },
    'Princess Poppy':{ photo: 'images/PrincessPoppyS15CastMug.webp', fashion: 8, design: 7, performance: 7, comedy: 8, acting: 6, improv: 6, lipsync: 7 },
    'Sugar':{ photo: 'images/SugarS15CastMug.webp', fashion: 10, design: 7, performance: 5, comedy: 5, acting: 6, improv: 6, lipsync: 5},
    'Irene the Alien':{ photo: 'images/IrenetheAlienAS10CastMug.webp', fashion: 13, design: 8, performance: 12, comedy: 12, acting: 10, improv: 14, lipsync: 9 },
    'Willow Pill':{photo:'images/WillowPillS14CastMug.webp', fashion:13,design: 12, performance: 11, comedy: 12, acting: 13, improv: 10, lipsync: 9 },
    'Lady Camden':{photo:'images/LadyCamdenS14CastMug.webp', fashion:11,design: 11, performance: 12, comedy: 11, acting: 14, improv: 10, lipsync: 10 },
    'Angeria Paris VanMicheals':{photo:'images/AngeriaParisVanMichealsAS9CastMug.webp', fashion:12,design: 11, performance: 12, comedy: 13, acting: 14, improv: 12, lipsync: 10 },
    'Bosco':{photo:'images/BoscoAS10CastMug.webp', fashion:13,design: 12, performance: 12, comedy: 14, acting: 12, improv: 14, lipsync: 10 },
    'Daya Betty':{photo:'images/DayaBettyAS10CastMug.webp', fashion:11,design: 11, performance: 11, comedy: 9, acting: 12, improv: 9, lipsync: 8 },
    'DeJa Skye':{photo:'images/DeJaSkyeAS10CastMug.webp', fashion:8,design: 6, performance: 9, comedy: 12, acting: 11, improv: 12, lipsync: 9 },
    'Jorgeous':{photo:'images/JorgeousAS10CastMug.webp', fashion:13,design: 10, performance: 13, comedy: 10, acting: 12, improv: 11, lipsync: 13},
    'Jasmine Kennedie':{photo:'images/JasmineKennedieS14CastMug.webp', fashion:8,design: 6, performance: 9, comedy: 6, acting: 7, improv: 5, lipsync: 13},
    'Kerri Colby':{photo:'images/KerriColbyAS10CastMug.webp', fashion:10,design: 7, performance: 8, comedy: 8, acting: 8, improv: 8, lipsync: 7},
    'Maddy Morphosis':{photo:'images/MaddyMorphosisS14CastMug.webp', fashion:6,design: 5, performance: 7, comedy: 10, acting:9, improv: 10, lipsync: 5},
    'Orion Story':{photo:'images/OrionStoryS14CastMug.webp', fashion:6,design: 6, performance: 5, comedy: 5, acting: 6, improv: 5, lipsync: 5},
    'Kornbread "The Snack" Jeté':{photo:'images/KornbreadJetS14CastMug.webp', fashion:7,design: 7, performance: 10, comedy: 10, acting: 7, improv: 7, lipsync: 7},
    'Alyssa Hunter':{photo:'images/AlyssaHunterAS10CastMug.webp', fashion:8,design: 9, performance: 7, comedy: 6, acting: 5, improv: 7, lipsync: 6},
    'June Jambalaya':{photo:'images/JuneJambalayaS14CastMug.webp', fashion:5,design: 4, performance: 6, comedy: 6, acting: 6, improv: 6, lipsync: 6},
    "Symone":{photo:'images/SymoneS13CastMug.webp', fashion:12,design: 12, performance: 12, comedy: 13, acting: 13, improv:11, lipsync: 11},
    "Kandy Muse":{photo:'images/KandyMuseAS8CastMug.webp', fashion:10,design: 7, performance: 10, comedy: 12, acting: 11, improv:11, lipsync: 13},
    "Gottmik":{photo:'images/GottmikAS9CastMug.webp', fashion:14,design: 11, performance: 7, comedy: 13, acting: 12, improv:13, lipsync: 7},
    "Rosé":{photo:'images/RoseS13CastMug.webp', fashion:10,design: 10, performance: 14, comedy: 13, acting: 13, improv:12, lipsync: 8},
    "Olivia Lux":{photo:'images/OliviaLuxAS10CastMug.webp', fashion:10,design: 11, performance: 13, comedy: 8, acting: 8, improv:10, lipsync: 11},
    "Utica Queen":{photo:'images/UticaQueenS13CastMug.webp', fashion:14,design: 15, performance: 9, comedy: 6, acting: 8, improv:6, lipsync: 10},
    "Tina Burner":{photo:'images/TinaBurnerAS10CastMug.webp', fashion:9,design: 12, performance: 11, comedy: 9, acting: 8, improv:9, lipsync: 10},
    "Denali":{photo:'images/DenaliAS10CastMug.webp', fashion:10,design: 8, performance: 14, comedy: 11, acting: 9, improv:10, lipsync: 13},
    "Elliott with 2 Ts":{photo:'images/ElliottWith2TsS13CastMug.webp', fashion:7,design: 7, performance: 12, comedy: 5, acting: 7, improv:5, lipsync: 11},
    "LaLa Ri":{photo:'images/LaLaRiAS8CastMug.webp', fashion:9,design: 8, performance: 12, comedy: 10, acting: 9, improv:13, lipsync: 12},
    "Tamisha Iman":{photo:'images/TamishaImanS13CastMug.webp', fashion:7,design: 7, performance: 8, comedy: 7, acting: 8, improv:7, lipsync: 7},
    "Joey Jay":{photo:'images/JoeyJayS13CastMug.webp', fashion:6,design:5, performance: 6, comedy: 7, acting: 8, improv:7, lipsync: 7},
    "Kahmora Hall":{photo:'images/KahmoraHallS13CastMug.webp', fashion:9,design: 6, performance: 6, comedy: 6, acting: 7, improv:6, lipsync: 6},
    "Alexis Saint-Pete":{photo:'images/AlexisSaintPeteDRUK5CastMug.webp', fashion:8,design: 5, performance: 7, comedy: 6, acting: 6, improv:6, lipsync: 7},
    "Miss Naomi Carter":{photo:'images/MissNaomiCarterDRUK5CastMug.webp', fashion:7,design: 4, performance: 8, comedy: 5, acting: 7, improv:4, lipsync: 7},
    "Banksie":{photo:'images/BanksieDRUK5CastMug.webp', fashion:12,design: 11, performance: 6, comedy: 7, acting: 6, improv:7, lipsync: 7},
    "Vicki Vivacious":{photo:'images/VickiVivaciousDRUK5CastMug.webp', fashion:10,design: 9, performance: 10, comedy: 6, acting: 10, improv:6, lipsync: 9},
    "Cara Melle":{photo:'images/CaraMelleDRUK5CastMug.webp', fashion:10,design: 7, performance: 13, comedy: 8, acting: 6, improv:9, lipsync: 11},
    "DeDeLicious":{photo:'images/DeDeLiciousDRUK5CastMug.webp', fashion:9,design: 9, performance: 12, comedy: 7, acting: 8, improv:7, lipsync: 12},
    "Tomara Thomas":{photo:'images/TomaraThomasDRUK5CastMug.webp', fashion:10,design: 10, performance: 12, comedy: 12, acting: 9, improv:12, lipsync: 10},
    "Michael Marouli":{photo:'images/MichaelMarouliDRUK5CastMug.webp', fashion:11,design: 9, performance: 12, comedy: 13, acting: 10, improv:13, lipsync: 10},
    "Ginger Johnson":{photo:'images/GingerJohnsonDRUK5CastMug.webp', fashion:10,design: 9, performance: 11, comedy: 13, acting: 11, improv:13, lipsync: 10},
    };

