/**
 * Список всех королев для симулятора.
 * Каждая королева: photo, fashion, design, performance, comedy, acting, improv, lipsync (1–15).
 */
window.queensDb = {
    'Arrietty': { photo: 'images/ArriettyS17CastMug.webp', fashion: 13, design: 13, performance: 8, comedy: 5, acting: 6, improv: 5, lipsync: 5, seasons:['US S17'] },
    'Kori King': { photo: 'images/KoriKingS17CastMug.webp', fashion: 8, design: 6, performance: 7, comedy: 9, acting: 9, improv: 9, lipsync: 9, seasons:['US S17'] },
    'Lydia B Kollins': { photo: 'images/LydiaBKollinsS17CastMug.webp', fashion: 12, design: 10, performance: 12, comedy: 11, acting: 9, improv: 11, lipsync: 12, seasons:['US S17'] },
    'Jewels Sparkles': { photo: 'images/JewelsSparklesS17CastMug.webp', fashion: 12, design: 10, performance: 12, comedy: 11, acting: 10, improv: 11, lipsync: 11, seasons:['US S17'] },
    'Acacia Forgot': { photo: 'images/AcaciaForgotS17CastMug.webp', fashion: 7, design: 7, performance: 5, comedy: 8, acting: 7, improv: 8, lipsync: 7, seasons:['US S17'] },
    'Crystal Envy': { photo: 'images/CrystalEnvyS17CastMug.webp', fashion: 9, design: 10, performance: 10, comedy: 6, acting: 9, improv: 6, lipsync: 9, seasons:['US S17'] },
    'Hormona Lisa': { photo: 'images/HormonaLisaS17CastMug.webp', fashion: 7, design: 8, performance: 6, comedy: 7, acting: 10, improv: 7, lipsync: 4, seasons:['US S17'] },
    'Joella': { photo: 'images/JoellaS17CastMug.webp', fashion: 5, design: 5, performance: 6, comedy: 7, acting: 7, improv: 7, lipsync:7, seasons:['US S17'] },
    'Lana Ja\'Rae': { photo: 'images/LanaJaRaeS17CastMug.webp', fashion: 8, design: 6, performance: 8, comedy: 8, acting: 7, improv: 7, lipsync: 12, seasons:['US S17'] },
    'Lexi': { photo: 'images/LexiS17CastMug.webp', fashion: 11, design: 11, performance: 13, comedy: 11, acting: 12, improv: 11, lipsync: 12, seasons:['US S17'] },
    'Lucky Starzzz': { photo: 'images/LuckyStarzzzS17CastMug.webp', fashion: 8, design: 4, performance: 5, comedy: 6, acting: 6, improv: 6, lipsync: 5, seasons:['US S17'] },
    'Onya Nurve': { photo: 'images/OnyaNurveS17CastMug.webp', fashion: 10, design: 10, performance: 14, comedy: 14, acting: 14, improv: 13, lipsync: 10, seasons:['US S17'] },
    'Sam Star': { photo: 'images/SamStarS17CastMug.webp', fashion: 12, design: 14, performance: 12, comedy: 10, acting: 11, improv: 11, lipsync: 10, seasons:['US S17'] },
    'Suzie Toot': { photo: 'images/SuzieTootS17CastMug.webp', fashion: 10, design: 8, performance: 13, comedy:10, acting: 14, improv: 10, lipsync: 8, seasons:['US S17'] },
    'Athena Dion': { photo: 'images/AthenaDionS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8, seasons:['US S18'] },
    'Briar Blush': { photo: 'images/BriarBlushS18CastMug.webp', fashion: 6,  design: 7,  performance: 8,  comedy:7, acting: 6, improv: 6, lipsync: 9, seasons:['US S18'] },
    'Ciara Myst':{ photo: 'images/CiaraMystS18CastMug.webp', fashion: 9,  design: 8,  performance: 6,  comedy: 7, acting: 6, improv: 6, lipsync: 6, seasons:['US S18'] },
    'Darlene Mitchell':{ photo: 'images/DarleneMitchellS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8, seasons:['US S18'] },
    'DD Fuego':{ photo: 'images/DDFuegoS18CastMug.webp', fashion: 5,  design: 4,  performance: 5,  comedy: 6, acting: 6, improv: 6, lipsync: 4, seasons:['US S18'] },
    'Discord Addams':{ photo: 'images/DiscordAddamsS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8, seasons:['US S18'] },
    'Jane Don\'t':{ photo: 'images/JaneDontS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8, seasons:['US S18'] },
    'Juicy Love Dion':{ photo: 'images/JuicyLoveDionS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8, seasons:['US S18'] },
    'Kenya Pleaser':{ photo: 'images/KenyaPleaserS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8, seasons:['US S18'] },
    'Mandy Mango':{ photo: 'images/MandyMangoS18CastMug.webp', fashion: 6,  design: 5,  performance: 8,  comedy: 6, acting: 6, improv: 6, lipsync: 9, seasons:['US S18'] },
    'Mia Starr':{ photo: 'images/MiaStarrS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8, seasons:['US S18'] },
    'Myki Meeks':{ photo: 'images/MykiMeeksS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8, seasons:['US S18'] },
    'Nini Coco':{ photo: 'images/NiniCocoS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8, seasons:['US S18'] },
    'Vita VonTesse Starr': { photo: 'images/VitaVonTesseStarrS18CastMug.webp', fashion: 7,  design: 7,  performance: 7,  comedy: 7, acting: 7, improv: 7, lipsync: 8, seasons:['US S18'] },
    'Amanda Tori Meating': { photo: 'images/AmAndaToriMeatingS16CastMug.webp', fashion: 6, design: 6, performance: 9, comedy: 7, acting: 7, improv: 7, lipsync: 8, seasons:['US S16'] },
    'Dawn':{photo: 'images/DawnS16CastMug.webp', fashion: 11, design: 11, performance: 8, comedy: 8, acting: 8, improv: 7, lipsync:6, seasons:['US S16'] },
    'Geneva Karr':{photo: 'images/GenevaKarrS16CastMug.webp', fashion: 6, design: 6, performance: 10, comedy: 6, acting: 6, improv: 6, lipsync:12, seasons:['US S16'] },
    'Hershii LiqCour-Jeté':{photo: 'images/HershiiLiqCour-JeteS16CastMug.webp', fashion: 4, design: 4, performance:6, comedy: 7, acting: 7, improv: 7, lipsync:4, seasons:['US S16'] },
    'Megami':{photo: 'images/MegamiS16CastMug.webp', fashion: 7, design: 7, performance:6, comedy: 8, acting: 8, improv: 9, lipsync:10, seasons:['US S16'] },
    'Mhi\'ya Iman Le\'Paige':{photo: 'images/MhiPaigeS16CastMug.webp', fashion: 6, design: 6, performance:12, comedy: 8, acting: 6, improv: 7, lipsync:13, seasons:['US S16'] },
    'Mirage':{photo: 'images/MirageS16CastMug.webp', fashion: 8, design: 8, performance:10, comedy: 6, acting: 4, improv: 6, lipsync:11, seasons:['US S16'] },
    'Morphine Love Dion':{photo: 'images/MorphineLoveDionS16CastMug.webp', fashion: 8, design: 8, performance:14, comedy: 9, acting: 7, improv: 9, lipsync:14, seasons:['US S16'] },
    'Nymphia Wind':{photo: 'images/NymphiaWindS16CastMug.webp', fashion: 14, design: 14, performance:11, comedy: 9, acting: 9, improv: 9, lipsync:11, seasons:['US S16'] },
    'Plane Jane':{photo: 'images/PlaneJaneS16CastMug.webp', fashion: 12, design: 10, performance:11, comedy: 13, acting: 11, improv: 12, lipsync:10, seasons:['US S16'] },
    'Plasma':{photo: 'images/PlasmaS16CastMug.webp', fashion: 9, design: 7, performance:11, comedy: 11, acting: 13, improv: 10, lipsync:7, seasons:['US S16'] },
    'Q':{photo: 'images/QS16CastMug.webp', fashion: 13, design: 13, performance:7, comedy: 9, acting: 10, improv: 9, lipsync:6, seasons:['US S16'] },
    'Sapphira Cristál':{photo: 'images/SapphiraCristS16CastMug.webp', fashion: 12, design: 10, performance:11, comedy: 13, acting: 11, improv: 13, lipsync:9, seasons:['US S16'] },
    'Xunami Muse':{photo: 'images/XunamiMuseS16CastMug.webp', fashion: 8, design: 8, performance:8, comedy: 8, acting: 8, improv: 8, lipsync:6, seasons:['US S16'] },
    'Dulce':{photo: 'images/DulceCDR6CastMug.webp', fashion: 7, design: 7, performance:10, comedy: 7, acting: 9, improv: 6, lipsync:10, seasons:['CDR S6'] },
    'Eboni La\'Belle':{photo: 'images/EboniCDR6CastMug.webp', fashion: 10, design: 6, performance:14, comedy: 11, acting: 13, improv: 12, lipsync:15, seasons:['CDR S6'] },
    'Hazel':{photo: 'images/HazelCDR6CastMug.webp', fashion: 9, design: 8, performance:9, comedy: 5, acting: 6, improv: 5, lipsync:8, seasons:['CDR S6'] },
    'Karamilk':{photo: 'images/KaramilkCDR6CastMug.webp', fashion: 9, design: 10, performance:11, comedy: 9, acting: 9, improv: 7, lipsync:10, seasons:['CDR S6'] },
    'Mya Foxx':{photo: 'images/MyaFoxxCDR6CastMug.webp', fashion: 8, design: 7, performance:7, comedy: 13, acting: 9, improv: 13, lipsync:5, seasons:['CDR S6'] },
    'Paolo Perfección': {photo: 'images/PaoloPerfeccionCDR6CastMug.webp', fashion: 7, design: 7, performance:6, comedy: 6, acting: 5, improv: 7, lipsync:5, seasons:['CDR S6'] },
    'PM':{photo: 'images/PMCDR6CastMug.webp', fashion: 6, design: 4, performance:13, comedy: 8, acting: 8, improv: 11, lipsync:12, seasons:['CDR S6'] },     
    'Saltina Shaker':{photo: 'images/SaltinaShakerCDR6CastMug.webp', fashion: 11, design: 5, performance:13, comedy: 13, acting: 13, improv: 10, lipsync:12, seasons:['CDR S6'] },
    'Sami Landri':{photo: 'images/SamiLandriCDR6CastMug.webp', fashion: 11, design: 8, performance:9, comedy: 11, acting: 9, improv: 13, lipsync:9, seasons:['CDR S6'] },
    'Star Doll':{photo: 'images/StarDollCDR6CastMug.webp', fashion: 7, design: 6, performance:10, comedy: 7, acting: 7, improv: 7, lipsync:11, seasons:['CDR S6'] },
    'Van Goth':{photo: 'images/VanGothCDR6CastMug.webp', fashion: 14, design: 15, performance:10, comedy: 8, acting: 8, improv: 8, lipsync:10, seasons:['CDR S6'] },
    'Velma Jones':{photo: 'images/VelmaJonesCDR6CastMug.webp', fashion: 10, design: 8, performance:10, comedy: 11, acting: 10, improv: 9, lipsync:8, seasons:['CDR S6'] },
    'Bones':{photo: 'images/BonesDRUK7CastMug.webp', fashion: 13, design: 11, performance:12, comedy: 11, acting: 10, improv: 9, lipsync:13, seasons:['UK 7'] },
    'Elle Vosque':{photo: 'images/ElleVosqueDRUK7CastMug.webp', fashion: 11, design: 9, performance:13, comedy: 12, acting: 13, improv: 12, lipsync:10, seasons:['UK 7'] },
    'Catrin Feelings':{photo: 'images/CatrinFeelingsDRUK7CastMug.webp', fashion: 8, design: 9, performance:9, comedy: 10, acting: 12, improv: 10, lipsync:9, seasons:['UK 7'] },
    'Silllexa Diction':{photo: 'images/SilllexaDictionDRUK7CastMug.webp', fashion: 12, design: 10, performance:10, comedy: 8, acting: 7, improv: 8, lipsync:8, seasons:['UK 7'] },
    'Tayris Mongardi':{photo: 'images/TayrisMongardiDRUK7CastMug.webp', fashion: 8, design: 7, performance:13, comedy: 8, acting: 8, improv: 8, lipsync:12, seasons:['UK 7'] },
    'Bonnie Ann Clyde':{photo: 'images/BonnieAnnClydeDRUK7CastMug.webp', fashion: 6, design: 6, performance:10, comedy: 14, acting: 14, improv: 14, lipsync:7, seasons:['UK 7'] },
    'Paige Three':{photo: 'images/PaigeThreeDRUK7CastMug.webp', fashion: 11, design: 9, performance:14, comedy: 6, acting: 11, improv: 6, lipsync:12, seasons:['UK 7'] },
    'Sally™':{photo: 'images/SallyDRUK7CastMug.webp', fashion: 11, design: 12, performance:6, comedy: 7, acting: 12, improv: 7, lipsync:7, seasons:['UK 7'] },
    'Chai T Grande':{photo: 'images/ChaiTGrandeDRUK7CastMug.webp', fashion: 8, design: 8, performance:8, comedy: 7, acting: 6, improv: 7, lipsync:7, seasons:['UK 7'] },
    'Nyongbella':{photo: 'images/NyongbellaDRUK7CastMug.webp', fashion: 7, design: 8, performance:8, comedy: 7, acting: 4, improv: 6, lipsync:8, seasons:['UK 7'] },
    'Viola':{photo: 'images/ViolaDRUK7CastMug.webp', fashion: 7, design: 5, performance:6, comedy: 6, acting: 6, improv: 10, lipsync:7, seasons:['UK 7'] },
    'Pasty':{photo: 'images/PastyDRUK7CastMug.webp', fashion: 5, design: 3, performance:5, comedy: 6, acting:6, improv: 6, lipsync:4, seasons:['UK 7'] },
    'Gawdland':{photo: 'images/GawdlandUKvsTW3CastMug.webp', fashion: 11, design: 9, performance:13, comedy: 10, acting: 13, improv: 10, lipsync:10, seasons:['UKvsTW3'] },
    'Fontana':{photo: 'images/FontanaUKvsTW3CastMug.webp', fashion: 10, design: 8, performance:12, comedy: 9, acting: 12, improv: 9, lipsync:12, seasons:['UKvsTW3'] },
    'Mariah Balenciaga':{photo: 'images/MariahBalenciagaUKvsTW3CastMug.webp', fashion: 7, design: 8, performance:8, comedy: 6, acting: 8, improv: 5, lipsync:7, seasons:['UKvsTW3'] },
    'Kate Butch':{photo: 'images/KateButchUKvsTW3CastMug.webp', fashion: 7, design: 7, performance:11, comedy: 12, acting: 14, improv: 11, lipsync:6, seasons:['UKvsTW3', 'UK 5'] },
    'Serena Morena':{photo: 'images/SerenaMorenaUKvsTW3CastMug.webp', fashion: 7, design: 5, performance:4, comedy: 5, acting: 5, improv: 6, lipsync:7, seasons:['UKvsTW3'] },
    'Sminty Drop':{photo: 'images/SmintyDropUKvsTW3CastMug.webp', fashion: 11, design: 11, performance:6, comedy: 5, acting: 6, improv: 4, lipsync:6, seasons:['UKvsTW3'] },
    'Zahirah Zapanta':{photo: 'images/ZahirahZapantaUKvsTW3CastMug.webp', fashion: 6, design: 5, performance:7, comedy: 6, acting: 5, improv: 4, lipsync:7, seasons:['UKvsTW3', 'UK 6'] },
    'Minty Fresh':{photo: 'images/MintyFreshUKvsTW3CastMug.webp', fashion: 12, design: 11, performance:10, comedy: 6, acting: 8, improv: 7, lipsync:7, seasons:['UKvsTW3'] },
    'The Only Naomy':{photo: 'images/TheOnlyNaomyUKvsTW3CastMug.webp', fashion: 8, design: 8, performance:4, comedy: 6, acting: 6, improv: 6, lipsync:4, seasons:['UKvsTW3'] },
    'Melinda Verga':{photo: 'images/MelindaVergaUKvsTW3CastMug.webp', fashion: 7, design: 5, performance:12, comedy: 13, acting: 12, improv: 13, lipsync:11, seasons:['UKvsTW3'] },
    'Actavia':{photo: 'images/ActaviaDRUK6CastMug.webp', fashion: 5, design: 6, performance:10, comedy: 7, acting: 7, improv: 5, lipsync:12, seasons:['UK 6'] },
    'Chanel O\'Conor':{photo: 'images/ChanelOConorDRUK6CastMug.webp', fashion: 11, design: 12, performance:9, comedy: 6, acting: 9, improv: 5, lipsync:8, seasons:['UK 6'] },
    'Charra Tea':{photo: 'images/CharraTeaDRUK6CastMug.webp', fashion: 7, design: 7, performance:8, comedy: 9, acting: 8, improv: 10, lipsync:8, seasons:['UK 6'] },
    'Dita Garbo':{photo: 'images/DitaGarboDRUK6CastMug.webp', fashion: 8, design: 6, performance:6, comedy: 6, acting: 4, improv: 6, lipsync:6, seasons:['UK 6'] },
    'Kiki Snatch':{photo: 'images/KikiSnatchDRUK6CastMug.webp', fashion: 6, design: 6, performance:12, comedy: 6, acting: 6, improv: 5, lipsync:12, seasons:['UK 6'] },
    'Kyran Thrax':{photo: 'images/KyranThraxDRUK6CastMug.webp', fashion: 11, design: 10, performance:12, comedy: 13, acting: 13, improv: 12, lipsync:10, seasons:['UK 6'] },
    'La Voix':{photo: 'images/LaVoixDRUK6CastMug.webp', fashion: 10, design: 9, performance:12, comedy: 14, acting:13, improv: 14, lipsync:10, seasons:['UK 6'] },
    'Lill':{photo: 'images/LillDRUK6CastMug.webp', fashion: 12, design: 12, performance:8, comedy: 10, acting:9, improv: 10, lipsync:11, seasons:['UK 6'] },
    'Marmalade':{photo:'images/MarmaladeDRUK6CastMug.webp', fashion: 14, design: 13, performance:9, comedy: 11, acting: 11, improv: 11, lipsync:8, seasons:['UK 6'] },
    'Rileasa Slaves':{photo:'images/RileasaSlavesDRUK6CastMug.webp',fashion:9, design:8, performance:13,comedy:7,acting:12,improv:7,lipsync:14, seasons:['UK 6'] },
    'Saki Yew':{photo:'images/SakiYewDRUK6CastMug.webp',fashion:7, design:6, performance:6,comedy:6,acting:6,improv:6,lipsync:6, seasons:['UK 6'] },
    'Sasha Colby': { photo: 'images/SashaColbyS15CastMug.webp', fashion: 12, design: 13, performance: 14, comedy: 13, acting: 13, improv: 13, lipsync: 14, seasons:['US S15'] },
    'Anetra':{ photo: 'images/AnetraS15CastMug.webp', fashion: 11, design: 13, performance: 14, comedy: 9, acting: 13, improv: 10, lipsync: 14, seasons:['US S15'] },
    'Luxx Noir London':{ photo: 'images/LuxxNoirLondonS15CastMug.webp', fashion: 13, design: 14, performance: 12, comedy: 12, acting: 11, improv: 12, lipsync: 12, seasons:['US S15'] },
    'Mistress Isabelle Brooks':{ photo: 'images/MistressIsabelleBrooksAS10CastMug.webp', fashion: 13, design: 13, performance: 11, comedy: 14, acting: 13, improv: 12, lipsync: 10, seasons:['US S15'] },
    'Loosey LaDuca':{ photo: 'images/LooseyLaDucaS15CastMug.webp', fashion: 10, design: 9, performance: 9, comedy: 14, acting: 10, improv: 14, lipsync: 9, seasons:['US S15'] },
    'Salina EsTitties':{ photo: 'images/SalinaEsTittiesS15CastMug.webp', fashion: 6, design: 6, performance: 8, comedy: 9, acting: 8, improv: 8, lipsync: 9, seasons:['US S15'] },
    'Marcia Marcia Marcia':{ photo: 'images/MarciaMarciaMarciaS15CastMug.webp', fashion: 9, design: 9, performance: 11, comedy: 10, acting: 12, improv: 11, lipsync: 11, seasons:['US S15'] },
    'Malaysia Babydoll Foxx':{ photo: 'images/MalaysiaBabydollFoxxS15CastMug.webp', fashion: 9, design: 9, performance: 8, comedy: 9, acting: 13, improv: 8, lipsync: 8, seasons:['US S15'] },
    'Spice':{ photo: 'images/SpiceS15CastMug.webp', fashion: 10, design: 5, performance: 10, comedy: 6, acting: 7, improv: 6, lipsync: 6, seasons:['US S15'] },
    'Jax':{ photo: 'images/JaxS15CastMug.webp', fashion: 7, design: 6, performance: 13, comedy: 8, acting: 6, improv: 7, lipsync: 14, seasons:['US S15'] },
    'Aura Mayari':{ photo: 'images/AuraMayariS15CastMug.webp', fashion: 7, design: 7, performance: 11, comedy: 7, acting: 4, improv: 7, lipsync: 10, seasons:['US S15'] },
    'Robin Fierce':{ photo: 'images/RobinFierceS15CastMug.webp', fashion: 7, design: 8, performance: 6, comedy: 5, acting: 5, improv: 5, lipsync: 7, seasons:['US S15'] },
    'Amethyst':{ photo: 'images/AmethystS15CastMug.webp', fashion: 7, design: 5, performance: 8, comedy: 9, acting: 6, improv: 7, lipsync: 10, seasons:['US S15'] },
    'Princess Poppy':{ photo: 'images/PrincessPoppyS15CastMug.webp', fashion: 8, design: 7, performance: 7, comedy: 8, acting: 6, improv: 6, lipsync: 7, seasons:['US S15'] },
    'Sugar':{ photo: 'images/SugarS15CastMug.webp', fashion: 10, design: 7, performance: 5, comedy: 5, acting: 6, improv: 6, lipsync: 5, seasons:['US S15'] },
    'Irene the Alien':{ photo: 'images/IrenetheAlienAS10CastMug.webp', fashion: 13, design: 8, performance: 12, comedy: 12, acting: 10, improv: 14, lipsync: 9, seasons:['US S15'] },
    'Willow Pill':{photo:'images/WillowPillS14CastMug.webp', fashion:13,design: 12, performance: 11, comedy: 12, acting: 13, improv: 10, lipsync: 9, seasons:['US S14'] },
    'Lady Camden':{photo:'images/LadyCamdenS14CastMug.webp', fashion:11,design: 11, performance: 12, comedy: 11, acting: 14, improv: 10, lipsync: 10, seasons:['US S14'] },
    'Angeria Paris VanMicheals':{photo:'images/AngeriaParisVanMichealsAS9CastMug.webp', fashion:12,design: 11, performance: 12, comedy: 13, acting: 14, improv: 12, lipsync: 10, seasons:['US S14'] },
    'Bosco':{photo:'images/BoscoAS10CastMug.webp', fashion:13,design: 12, performance: 12, comedy: 14, acting: 12, improv: 14, lipsync: 10, seasons:['US S14'] },
    'Daya Betty':{photo:'images/DayaBettyAS10CastMug.webp', fashion:11,design: 11, performance: 11, comedy: 9, acting: 12, improv: 9, lipsync: 8, seasons:['US S14'] },
    'DeJa Skye':{photo:'images/DeJaSkyeAS10CastMug.webp', fashion:8,design: 6, performance: 9, comedy: 12, acting: 11, improv: 12, lipsync: 9, seasons:['US S14'] },
    'Jorgeous':{photo:'images/JorgeousAS10CastMug.webp', fashion:13,design: 10, performance: 13, comedy: 10, acting: 12, improv: 11, lipsync: 13, seasons:['US S14']},
    'Jasmine Kennedie':{photo:'images/JasmineKennedieS14CastMug.webp', fashion:8,design: 6, performance: 9, comedy: 6, acting: 7, improv: 5, lipsync: 13, seasons:['US S14'] },
    'Kerri Colby':{photo:'images/KerriColbyAS10CastMug.webp', fashion:10,design: 7, performance: 8, comedy: 8, acting: 8, improv: 8, lipsync: 7, seasons:['US S14']},
    'Maddy Morphosis':{photo:'images/MaddyMorphosisS14CastMug.webp', fashion:6,design: 5, performance: 7, comedy: 10, acting:9, improv: 10, lipsync: 5, seasons:['US S14'] },
    'Orion Story':{photo:'images/OrionStoryS14CastMug.webp', fashion:6,design: 6, performance: 5, comedy: 5, acting: 6, improv: 5, lipsync: 5, seasons:['US S14'] },
    'Kornbread "The Snack" Jeté':{photo:'images/KornbreadJetS14CastMug.webp', fashion:7,design: 7, performance: 10, comedy: 10, acting: 7, improv: 7, lipsync: 7, seasons:['US S14'] },
    'Alyssa Hunter':{photo:'images/AlyssaHunterAS10CastMug.webp', fashion:8,design: 9, performance: 7, comedy: 6, acting: 5, improv: 7, lipsync: 6, seasons:['US S14']},
    'June Jambalaya':{photo:'images/JuneJambalayaS14CastMug.webp', fashion:5,design: 4, performance: 6, comedy: 6, acting: 6, improv: 6, lipsync: 6, seasons:['US S14'] },
    "Symone":{photo:'images/SymoneS13CastMug.webp', fashion:12,design: 12, performance: 12, comedy: 13, acting: 13, improv:11, lipsync: 11, seasons:['US S13'] },
    "Kandy Muse":{photo:'images/KandyMuseAS8CastMug.webp', fashion:10,design: 7, performance: 10, comedy: 12, acting: 11, improv:11, lipsync: 13, seasons:['US S13']},
    "Gottmik":{photo:'images/GottmikAS9CastMug.webp', fashion:14,design: 11, performance: 7, comedy: 13, acting: 12, improv:13, lipsync: 7, seasons:['US S13']},
    "Rosé":{photo:'images/RoseS13CastMug.webp', fashion:10,design: 10, performance: 14, comedy: 13, acting: 13, improv:12, lipsync: 8, seasons:['US S13'] },
    "Olivia Lux":{photo:'images/OliviaLuxAS10CastMug.webp', fashion:10,design: 11, performance: 13, comedy: 8, acting: 8, improv:10, lipsync: 11, seasons:['US S13']},
    "Utica Queen":{photo:'images/UticaQueenS13CastMug.webp', fashion:14,design: 15, performance: 9, comedy: 6, acting: 8, improv:6, lipsync: 10, seasons:['US S13'] },
    "Tina Burner":{photo:'images/TinaBurnerAS10CastMug.webp', fashion:9,design: 12, performance: 11, comedy: 9, acting: 8, improv:9, lipsync: 10, seasons:['US S13']},
    "Denali":{photo:'images/DenaliAS10CastMug.webp', fashion:10,design: 8, performance: 14, comedy: 11, acting: 9, improv:10, lipsync: 13, seasons:['US S13']},
    "Elliott with 2 Ts":{photo:'images/ElliottWith2TsS13CastMug.webp', fashion:7,design: 7, performance: 12, comedy: 5, acting: 7, improv:5, lipsync: 11, seasons:['US S13'] },
    "LaLa Ri":{photo:'images/LaLaRiAS8CastMug.webp', fashion:9,design: 8, performance: 12, comedy: 10, acting: 9, improv:13, lipsync: 12, seasons:['US S13']},
    "Tamisha Iman":{photo:'images/TamishaImanS13CastMug.webp', fashion:7,design: 7, performance: 8, comedy: 7, acting: 8, improv:7, lipsync: 7, seasons:['US S13'] },
    "Joey Jay":{photo:'images/JoeyJayS13CastMug.webp', fashion:6,design:5, performance: 6, comedy: 7, acting: 8, improv:7, lipsync: 7, seasons:['US S13'] },
    "Kahmora Hall":{photo:'images/KahmoraHallS13CastMug.webp', fashion:9,design: 6, performance: 6, comedy: 6, acting: 7, improv:6, lipsync: 6, seasons:['US S13'] },
    "Alexis Saint-Pete":{photo:'images/AlexisSaintPeteDRUK5CastMug.webp', fashion:8,design: 5, performance: 7, comedy: 6, acting: 6, improv:6, lipsync: 7, seasons:['UK 5'] },
    "Miss Naomi Carter":{photo:'images/MissNaomiCarterDRUK5CastMug.webp', fashion:7,design: 4, performance: 8, comedy: 5, acting: 7, improv:4, lipsync: 7, seasons:['UK 5'] },
    "Banksie":{photo:'images/BanksieDRUK5CastMug.webp', fashion:12,design: 11, performance: 6, comedy: 7, acting: 6, improv:7, lipsync: 7, seasons:['UK 5'] },
    "Vicki Vivacious":{photo:'images/VickiVivaciousDRUK5CastMug.webp', fashion:10,design: 9, performance: 10, comedy: 6, acting: 10, improv:6, lipsync: 9, seasons:['UK 5'] },
    "Cara Melle":{photo:'images/CaraMelleDRUK5CastMug.webp', fashion:10,design: 7, performance: 13, comedy: 8, acting: 6, improv:9, lipsync: 11, seasons:['UK 5'] },
    "DeDeLicious":{photo:'images/DeDeLiciousDRUK5CastMug.webp', fashion:9,design: 9, performance: 12, comedy: 7, acting: 8, improv:7, lipsync: 12, seasons:['UK 5'] },
    "Tomara Thomas":{photo:'images/TomaraThomasDRUK5CastMug.webp', fashion:10,design: 10, performance: 12, comedy: 12, acting: 9, improv:12, lipsync: 10, seasons:['UK 5'] },
    "Michael Marouli":{photo:'images/MichaelMarouliDRUK5CastMug.webp', fashion:11,design: 9, performance: 12, comedy: 13, acting: 10, improv:13, lipsync: 10, seasons:['UK 5'] },
    "Ginger Johnson":{photo:'images/GingerJohnsonDRUK5CastMug.webp', fashion:10,design: 9, performance: 11, comedy: 13, acting: 11, improv:13, lipsync: 10, seasons:['UK 5'] },
    "Penny Tration":{photo:'images/PennyTrationS5CastMug.webp', fashion:5,design: 4, performance:5, comedy: 6, acting: 6, improv:6, lipsync: 5, seasons:['US S5'] },
    "Serena ChaCha":{photo:'images/SerenaChaChaAS6CastMug.webp', fashion:6,design: 5, performance: 5, comedy: 5, acting: 5, improv:6, lipsync: 6, seasons:['US S5']},
    "Monica Beverly Hillz":{photo:'images/MonicaBeverlyHillzAS8CastMug.webp', fashion:7,design: 7, performance: 5, comedy: 5, acting: 6, improv:4, lipsync: 6, seasons:['US S5']},
    "Vivienne Pinay":{photo:'images/ViviennePinayS5CastMug.webp', fashion:7,design: 7, performance: 5, comedy: 6, acting: 7, improv:6, lipsync: 5, seasons:['US S5'] },
    "Honey Mahogany":{photo:'images/HoneyMahoganyS5CastMug.webp', fashion:7,design: 7, performance: 5, comedy: 7, acting: 7, improv:6, lipsync: 5, seasons:['US S5'] },
    "Lineysha Sparx":{photo:'images/LineyshaSparxS5CastMug.webp', fashion:9,design: 12, performance: 8, comedy: 6, acting: 11, improv:7, lipsync: 7, seasons:['US S5'] },
    "Jade Jolie":{photo:'images/JadeJolieTitans2CastMug.webp', fashion:9,design: 8, performance: 8, comedy: 8, acting: 7, improv:8, lipsync: 9, seasons:['US S5']},
    "Ivy Winters":{photo:'images/IvyWintersS5CastMug.webp', fashion:12,design: 11, performance: 12, comedy: 7, acting: 10, improv:7, lipsync: 8, seasons:['US S5']},
    "Alyssa Edwards":{photo:'images/AlyssaEdwardsGAS1CastMug.webp', fashion:11,design: 8, performance: 12, comedy: 11, acting: 10, improv:10, lipsync: 13, seasons:['US S5']},
    "Coco Montrese":{photo:'images/CocoMontreseAS2CastMug.webp', fashion:8,design: 8, performance: 11, comedy: 11, acting: 8, improv:11, lipsync: 14, seasons:['US S5']},
    "Detox":{photo:'images/DetoxAS2CastMug.webp', fashion:12,design: 9, performance: 12, comedy: 12, acting: 10, improv:12, lipsync: 13, seasons:['US S5']},
    "Alaska":{photo:'images/AlaskaAS2CastMug.webp', fashion:11,design: 11, performance: 11, comedy: 14, acting: 13, improv:13, lipsync: 9, seasons:['US S5']},
    "Jinkx Monsoon":{photo:'images/JinkxMonsoonAS7CastMug.webp', fashion:11,design: 9, performance: 11, comedy: 15, acting: 14, improv:15, lipsync: 9, seasons:['US S5']},
    "Roxxxy Andrews":{photo:'images/RoxxxyAndrewsAS9CastMug.webp', fashion:13,design: 13, performance: 11, comedy: 11, acting: 11, improv:11, lipsync: 12, seasons:['US S5']},
    "Kelly Mantle":{photo:'images/KellyMantleS6CastMug.webp', fashion:5,design: 4, performance: 5, comedy: 6, acting: 8, improv:7, lipsync: 5, seasons:['US S6']},
    "Magnolia Crawford":{photo:'images/MagnoliaCrawfordS6CastMug.webp', fashion:5,design: 3, performance: 5, comedy: 6, acting: 6, improv:6, lipsync: 4, seasons:['US S6']},
    "Vivacious":{photo:'images/VivaciousS6CastMug.webp', fashion:6,design: 5, performance: 6, comedy: 6, acting: 5, improv:6, lipsync: 7, seasons:['US S6']},
    "April Carrión":{photo:'images/AprilCarriS6CastMug.webp', fashion:8,design: 9, performance: 6, comedy: 7, acting: 7, improv:7, lipsync: 8, seasons:['US S6']},
    "Gia Gunn":{photo:'images/GiaGunnAS4CastMug.webp', fashion:10,design: 9, performance: 9, comedy: 5, acting: 8, improv:4, lipsync: 6, seasons:['US S6']},
    "Milk":{photo:'images/MilkAS3CastMug.webp', fashion:9,design: 9, performance: 8, comedy: 6, acting: 8, improv:5, lipsync: 6, seasons:['US S6']},
    "Laganja Estranja":{photo:'images/LaganjaEstranjaS6CastMug.webp', fashion:9,design: 8, performance: 11, comedy: 7, acting: 9, improv:7, lipsync: 14, seasons:['US S6']},
    "Trinity K. Bonet":{photo:'images/TrinityKBonetAS6CastMug.webp', fashion:10,design: 10, performance: 11, comedy: 10, acting: 12, improv:10, lipsync: 12, seasons:['US S6']},
    "Joslyn Fox":{photo:'images/JoslynFoxS6CastMug.webp', fashion:8,design: 7, performance: 11, comedy: 10, acting: 9, improv:8, lipsync: 10, seasons:['US S6']},
    "BenDeLaCreme":{photo:'images/BenDeLaCremeAS3CastMug.webp', fashion:11,design: 11, performance: 13, comedy: 14, acting: 12, improv:14, lipsync: 9, seasons:['US S6']},
    "Darienne Lake":{photo:'images/DarienneLakeAS8CastMug.webp', fashion:7,design: 6, performance: 9, comedy: 9, acting: 10, improv:9, lipsync: 11, seasons:['US S6']},
    "Courtney Act":{photo:'images/CourtneyActS6CastMug.webp', fashion:12,design: 10, performance: 13, comedy: 11, acting: 12, improv:11, lipsync: 10, seasons:['US S6']},
    "Bianca Del Rio":{photo:'images/BiancaDelRioS6CastMug.webp', fashion:13,design: 12, performance: 11, comedy: 15, acting: 13, improv:13, lipsync: 10, seasons:['US S6']},
    "Adore Delano":{photo:'images/AdoreDelanoAS2CastMug.webp', fashion:11,design: 11, performance: 12, comedy: 12, acting: 11, improv:10, lipsync: 12, seasons:['US S6']},
    "Tempest DuJour":{photo:'images/TempestDuJourS7CastMug.webp', fashion:6,design: 4, performance: 5, comedy: 7, acting: 6, improv:6, lipsync: 5, seasons:['US S7']},
    "Frisbee Jenkins":{photo:'images/SashaBelleS7CastMug.webp', fashion:6,design: 5, performance: 4, comedy: 5, acting: 5, improv:5, lipsync: 6, seasons:['US S7']},
    "Jasmine Masters":{photo:'images/JasmineMastersAS4CastMug.webp', fashion:7,design: 5, performance: 6, comedy: 8, acting: 5, improv:7, lipsync: 6, seasons:['US S7']},
    "Mrs. Kasha Davis":{photo:'images/MrsKashaDavisAS8CastMug.webp', fashion:7,design: 7, performance: 7, comedy: 10, acting: 8, improv:9, lipsync: 6, seasons:['US S7']},
    "Kandy Ho":{photo:'images/KandyHoS7CastMug.webp', fashion:8,design: 5, performance: 6, comedy: 6, acting: 6, improv:6, lipsync: 9, seasons:['US S7']},
    "Max":{photo:'images/MaxS7CastMug.webp', fashion:12,design: 8, performance: 8, comedy: 9, acting: 12, improv:7, lipsync: 7, seasons:['US S7']},
    "Jaidynn Diore Fierce":{photo:'images/JaidynnDioreFierceS7CastMug.webp', fashion:8,design: 7, performance: 8, comedy: 9, acting: 7, improv:7, lipsync: 10, seasons:['US S7']},
    "Miss Fame":{photo:'images/MissFameS7CastMug.webp', fashion:13,design: 9, performance: 5, comedy: 5, acting: 7, improv:5, lipsync: 6, seasons:['US S7']},
    "Trixie Mattel":{photo:'images/TrixieMattelAS3CastMug.webp', fashion:12,design: 10, performance: 9, comedy: 12, acting: 11, improv:12, lipsync: 9, seasons:['US S7']},
    "Violet Chachki":{photo:'images/VioletChachkiS7CastMug.webp', fashion:15,design: 13, performance: 10, comedy: 8, acting: 9, improv:9, lipsync: 10, seasons:['US S7']},
    "Pearl":{photo:'images/PearlS7CastMug.webp', fashion:12,design: 9, performance: 7, comedy: 9, acting: 8, improv:8, lipsync: 7, seasons:['US S7']},
    "Katya":{photo:'images/KatyaAS2CastMug.webp', fashion:12,design: 8, performance: 12, comedy: 13, acting: 11, improv:13, lipsync: 12, seasons:['US S7']},
    "Kennedy Davenport":{photo:'images/KennedyDavenportCAvsTW2CastMug.webp', fashion:10,design: 9, performance: 13, comedy: 12, acting: 11, improv:12, lipsync: 13, seasons:['US S7']},
    "Ginger Minj":{photo:'images/GingerMinjAS10CastMug.webp', fashion:10,design: 10, performance: 11, comedy: 14, acting: 13, improv:12, lipsync: 9, seasons:['US S7']},
    "Jaymes Mansfield":{photo:'images/JaymesMansfieldAS8CastMug.webp', fashion:9,design: 7, performance: 5, comedy: 9, acting: 8, improv:8, lipsync: 6, seasons:['US S9']},
    "Kimora Blac":{photo:'images/KimoraBlacS9CastMug.webp', fashion:8,design: 5, performance: 6, comedy: 5, acting: 5, improv:5, lipsync: 6, seasons:['US S9']},
    "Charlie Hides":{photo:'images/CharlieHidesS9CastMug.webp', fashion:8,design: 6, performance: 5, comedy: 7, acting: 6, improv:5, lipsync: 3, seasons:['US S9']},
    "Eureka!":{photo:'images/EurekaCAvsTW2CastMug.webp', fashion:12,design: 9, performance: 10, comedy: 11, acting: 10, improv:11, lipsync: 12, seasons:['US S9']},
    "Cynthia Lee Fontaine":{photo:'images/CynthiaLeeFontaineAS10CastMug.webp', fashion:8,design: 8, performance: 9, comedy: 6, acting: 6, improv:7, lipsync: 8, seasons:['US S9']},
    "Aja":{photo:'images/AjaAS10CastMug.webp', fashion:10,design: 7, performance: 12, comedy: 10, acting: 7, improv:9, lipsync: 13, seasons:['US S9']},
    "Farrah Moan":{photo:'images/FarrahMoanAS4CastMug.webp', fashion:10,design: 7, performance: 6, comedy: 7, acting: 9, improv:8, lipsync: 7, seasons:['US S9']},
    "Valentina":{photo:'images/ValentinaHostMug.webp', fashion:13,design: 10, performance: 10, comedy: 8, acting: 10, improv:8, lipsync: 9, seasons:['US S9']},
    "Nina Bo'Nina Brown":{photo:'images/NinaBoninaBrownS9CastMug.webp', fashion:11,design: 9, performance: 8, comedy: 10, acting: 6, improv:9, lipsync: 10, seasons:['US S9']},
    "Alexis Michelle":{photo:'images/AlexisMichelleAS8CastMug.webp', fashion:9,design: 11, performance: 9, comedy: 10, acting: 9, improv:11, lipsync: 9, seasons:['US S9']},
    "Peppermint":{photo:'images/PeppermintS9CastMug.webp', fashion:10,design: 11, performance: 11, comedy: 12, acting: 10, improv:7, lipsync: 13, seasons:['US S9']},
    "Sasha Velour":{photo:'images/SashaVelourS9CastMug.webp', fashion:14,design: 12, performance: 10, comedy: 13, acting: 9, improv:12, lipsync: 13, seasons:['US S9']},
    "Shea Couleé":{photo:'images/SheaCouleAS7CastMug.webp', fashion:13,design: 12, performance: 12, comedy: 12, acting: 12, improv:11, lipsync: 11, seasons:['US S9']},
    "Trinity The Tuck":{photo:'images/TrinityTheTuckAS7CastMug.webp', fashion:13,design: 14, performance: 11, comedy: 13, acting: 11, improv:13, lipsync: 11, seasons:['US S9']},
    "Alisa Summers":{photo:'images/AlisaSummersS4CastMug.webp', fashion:5,design: 5, performance: 6, comedy: 6, acting: 6, improv:6, lipsync: 5, seasons:['US S4']},
    "Lashauwn Beyond":{photo:'images/LashauwnBeyondS4CastMug.webp', fashion:8,design: 10, performance: 5, comedy: 6, acting: 6, improv:6, lipsync: 5, seasons:['US S4']},
    "The Princess":{photo:'images/ThePrincessS4CastMug.webp', fashion:8,design: 10, performance: 6, comedy: 5, acting: 6, improv:6, lipsync: 6, seasons:['US S4']},
    "Madame LaQueer":{photo:'images/MadameLaQueerS4CastMug.webp', fashion:7,design: 8, performance: 9, comedy: 8, acting: 7, improv:10, lipsync: 6, seasons:['US S4']},
    "Milan":{photo:'images/MilanS4CastMug.webp', fashion:7,design: 6, performance: 10, comedy: 7, acting: 8, improv:8, lipsync: 10, seasons:['US S4']},
    "Jiggly Caliente":{photo:'images/JigglyCalienteJudgeMug.webp', fashion:7,design: 6, performance: 9, comedy: 8, acting: 10, improv:8, lipsync: 10, seasons:['US S4']},
    "Willam":{photo:'images/WillamS4CastMug.webp', fashion:10,design: 12, performance: 10, comedy: 11, acting: 11, improv:11, lipsync: 9, seasons:['US S4']},
    "Dida Ritz":{photo:'images/DidaRitzS4CastMug.webp', fashion:7,design: 7, performance: 8, comedy: 8, acting: 8, improv:6, lipsync: 13, seasons:['US S4']},
    "Kenya Michaels":{photo:'images/KenyaMichaelsS4CastMug.webp', fashion:8,design: 5, performance: 10, comedy: 5, acting: 7, improv:5, lipsync:10, seasons:['US S4']},
    "Latrice Royale":{photo:'images/LatriceRoyaleAS4CastMug.webp', fashion:10,design: 10, performance: 12, comedy: 11, acting: 12, improv:8, lipsync: 12, seasons:['US S4']},
    "Sharon Needles":{photo:'images/SharonNeedlesS4CastMug.webp', fashion:12,design: 12, performance: 10, comedy: 12, acting: 10, improv:11, lipsync: 8, seasons:['US S4']},
    "Chad Michaels":{photo:'images/ChadMichaelsAS1CastMug.webp', fashion:12,design: 12, performance: 12, comedy: 13, acting: 13, improv:13, lipsync: 10, seasons:['US S4']},
    "Jaremi Carey":{photo:'images/PhiPhiOHaraAS2CastMug.webp', fashion:13,design: 13, performance: 10, comedy: 8, acting: 12, improv:7, lipsync: 9, seasons:['US S4']},
    "Juice Boxx":{photo:'images/JuiceBoxxCDR1CastMug.webp', fashion:6,design: 4, performance: 7, comedy: 6, acting: 6, improv:6, lipsync: 6, seasons:['CDR S1']},
    "Kyne":{photo:'images/KyneCDR1CastMug.webp', fashion:7,design: 6, performance: 6, comedy: 6, acting: 5, improv:6, lipsync: 6, seasons:['CDR S1']},
    "Anastarzia Anaquway":{photo:'images/AnastarziaAnaquwayCDR1CastMug.webp', fashion:7,design: 8, performance: 5, comedy: 7, acting: 7, improv:7, lipsync: 6, seasons:['CDR S1']},
    "Tynomi Banks":{photo:'images/TynomiBanksCAvsTW2CastMug.webp', fashion:7,design: 6, performance: 9, comedy: 7, acting: 7, improv:7, lipsync: 9, seasons:['CDR S1']},
    "Kiara":{photo:'images/KiaraCDR1CastMug.webp', fashion:10,design: 9, performance: 8, comedy: 6, acting: 10, improv:6, lipsync: 9, seasons:['CDR S1']},
    "BOA":{photo:'images/BOACDR1CastMug.webp', fashion:9,design: 9, performance: 10, comedy: 7, acting: 8, improv:6, lipsync: 7, seasons:['CDR S1']},
    "Ilona Verley":{photo:'images/IlonaVerleyCDR1CastMug.webp', fashion:9,design: 7, performance: 9, comedy: 9, acting: 9, improv:8, lipsync: 9, seasons:['CDR S1']},
    "Lemon":{photo:'images/LemonCAvsTW2CastMug.webp', fashion:10,design: 9, performance: 13, comedy: 11, acting: 13, improv:12, lipsync: 12, seasons:['CDR S1']},
    "Jimbo":{photo:'images/JimboAS8CastMug.webp', fashion:13,design: 10, performance: 7, comedy: 13, acting: 13, improv:14, lipsync: 7, seasons:['CDR S1']},
    "Scarlett BoBo":{photo:'images/ScarlettBoBoCDR1CastMug.webp', fashion:12,design: 11, performance: 12, comedy: 10, acting: 10, improv:11, lipsync: 11, seasons:['CDR S1']},
    "Rita Baga":{photo:'images/RitaBagaCAvsTWCastMug.webp', fashion:11,design: 12, performance: 10, comedy: 12, acting: 12, improv:11, lipsync: 9, seasons:['CDR S1']},
    "Priyanka":{photo:'images/PriyankaCDR1CastMug.webp', fashion:11,design: 9, performance: 13, comedy: 10, acting: 10, improv:10, lipsync: 12, seasons:['CDR S1']},


    //"//":{photo:'images///.webp', fashion:7,design: 7, performance: 7, comedy: 7, acting: 7, improv:7, lipsync: 7, seasons:['']},

};
